### ISSUE TITLE
Why the solution time scales like O(NlogN), not O(N)？

### ISSUE THREAD

**Issue by learning-chip** [weymouth/GeometricMultigrid.jl#2]
First thanks for releasing the code -- very interesting work.

I remember clearly that MG for Possion equation has a complexity of O(N), as confirmed by Table 6.1 of  [Applied Numerical Linear Algebra](https://doi.org/10.1137/1.9781611971446). Indeed, your [benchmark figure](https://github.com/weymouth/GeometricMultigrid.jl/blob/main/benchmark/MGscaling.png) also looks closer to the O(N) line than O(NlogN) line.

A trivial calculation: a single V-cycle costs `N + N/d + N/d^2 + ... + N/d^l = O(N)` where `d` is reduction of grid size and `l` is the total level. MG converges in a constant number of V-cycles, given some error threshold.

**Comment by weymouth** [comment]
The number of operations per v-cycle is O(N), but the solution time performance is between O(N) and O(NlogN), and this has been my experience in general. I think you have to be careful to pick the correct stopping criterion to avoid the number of cycles increasing (very very) slowly with N. It could also have something to do with how the computer is dealing with the increasing size of the arrays.
